version: "3"

services:
    tx_front:
        image: tx_front
        container_name: tx_front
        build: ./frontend
        working_dir: /usr/src/app
        ports:
            - 4200:4200
        depends_on:
            - tx_nest
        env_file:
            'frontend/.env'
        restart: on-failure
        volumes:
            - tx_front_volume:/usr/src/app
            - tx_shared_volume:/usr/src/app/shared
        tty: true
        user: "${UID}:${GID}"
        networks:
            - ft_transcendence
    tx_nest:
        image: tx_nest
        container_name: tx_nest
        build: ./
        env_file:
            'backend/.env'
        ports:
            - 3000:3000
        restart: on-failure
        depends_on:
            - tx_postgres
        volumes:
            - tx_nest_volume:/usr/src/app
            - tx_shared_volume:/usr/src/app/shared
        tty: true
        networks:
            - ft_transcendence

    tx_postgres:
         env_file:
           - 'backend/.env'
         image: tx_postgres
         container_name: tx_postgres
         build: ./database
        #  environment:
        #    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        #    POSTGRES_USER: ${POSTGRES_USER}
        #    PGDATA: /var/lib/postgresql/data/database
         ports:
           - "5432:5432"
         tty: true
         volumes:
           - tx_postgres_volume:/var/lib/postgresql/data
           - /etc/localtime:/etc/localtime:ro
         networks:
           - ft_transcendence
         restart: always

    tx_adminer:
        image: adminer
        container_name: tx_adminer
        ports:
            - "8080:8080"
        tty: true
        restart: on-failure
        networks:
            - ft_transcendence

volumes:
    tx_nest_volume:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: "${PWD}/backend"
    tx_postgres_volume:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: "${PWD}/database/"
    tx_front_volume:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: "${PWD}/frontend"
    tx_shared_volume:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: "${PWD}/shared"
    tx_data_volume:
            driver: local
            driver_opts:
                type: none
                o: bind
                device: "{PWD}/data"

networks:
  ft_transcendence:
    name: ft_transcendence
    driver: bridge
