version: "3"

services:
    tx_front:
        image: tx_front
        container_name: tx_front
        build: ./front
        working_dir: /usr/src/app
        ports:
            - 4200:4200
        depends_on:
            - tx_nest
        env_file:
            'front/.env'
        restart: on-failure
        volumes:
            - tx_front_volume:/usr/src/app
        tty: true
        user: "${UID}:${GID}"
        networks:
            - ft_transcendence
    tx_nest:
        image: tx_nest
        container_name: tx_nest
        build: ./
        env_file:
            'srcs/.env'
        ports:
            - 3000:3000
        restart: on-failure
        depends_on:
            - tx_postgres
        volumes:
            - tx_nest_volume:/usr/src/app
        tty: true
        networks:
            - ft_transcendence

    tx_postgres:
         image: tx_postgres
         container_name: tx_postgres
         build: ./postgres
         environment:
           POSTGRES_PASSWORD: 1234
           POSTGRES_USER: postgres
           PGDATA: /var/lib/postgresql/data/database
         ports:
           - "5432:5432"
         tty: true
         volumes:
           - tx_postgres_volume:/var/lib/postgresql/data
         networks:
           - ft_transcendence

volumes:
    tx_nest_volume:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: "${PWD}/srcs"
    tx_postgres_volume:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: "${PWD}/postgres/"
    tx_front_volume:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: "${PWD}/front"

networks:
  ft_transcendence:
    name: ft_transcendence
    driver: bridge
