version: "3"

services:
    node-app:
        image: ft_transcendence
        container_name: ft_transcendence
        build: ./
        ports:
            - 3000:3000
        restart: on-failure
        command: npm run start
        volumes:
            - trans_volume:/usr/src/app
            - /usr/src/app/node_modules
        tty: true
        networks:
            - ft_transcendence

    postgres:
         image: postgres
         environment:
           POSTGRES_PASSWORD: 1234
           POSTGRES_USER: postgres
           PGUSER: postgres
         ports:
           - "5432:5432"
         networks:
           - "service"
         tty: true
         volumes:
           - postgres_volume:/var/lib/postgresql/
         networks:
             - ft_transcendence

volumes:
    trans_volume:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: "${PWD}/srcs"
    postgres_volume:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: "${PWD}/postgres"

networks:
  ft_transcendence:
    name: ft_transcendence
    driver: bridge
