FROM postgres

RUN mkdir -p /data
RUN mkdir -p ~/data
RUN mkdir -p ./data
RUN mkdir -p ./postgres/data
RUN mkdir -p /Users/albgarci/Documents/ft_transcendence/postgres
RUN mkdir -p /var/lib/postgresql/data

CMD ["postgres"]

