version: "3"

services:
    tx_front:
        image: tx_front
        container_name: tx_front
        build: ./
        ports:
            - 4200:4200
        environment:
            - NG_CLI_ANALYTICS="false"
        restart: on-failure
        volumes:
            - tx_front_volume:/usr/src/app
        tty: true
        networks:
            - ft_transcendence

volumes:
    tx_front_volume:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: "${PWD}"

networks:
  ft_transcendence:
    name: ft_transcendence
    driver: bridge
